medicine/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import settings
from rest_framework import routers
from medicineMain import views

router = routers.DefaultRouter()
router.register(r'casehistory', views.CaseHistoryViewSet)
router.register(r'symptom', views.SymptomViewSet)
router.register(r'address', views.AddressViewSet)
router.register(r'messages', views.MessagesViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
url(r'^messages/', views.messages),
url(r'^scrollimage/', views.scrollImage),
url(r'^indeximage/', views.indexImage),
url(r'^imageupapi/', views.imageUpApi),
    url(r'^wxlogin/', views.wxLogin),
    url(r'^userinfo/', views.userInfo),
url(r'^onlogin/', views.onLogin),
url(r'^code/', views.code),
url(r'^index/', views.index),
url(r'^bindCellPhone/', views.bindCellPhone),
url(r'^caseOrder/', views.caseOrder),
url(r'^caseTest/', views.caseTest),
url(r'^wxindex/', views.wxindex),

url(r'^myAddress/', views.myAddress),
url(r'^page10070/', views.page10070),
url(r'^addAddress/', views.addAddress),
url(r'^userinfo1/', views.userinfo),


url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT})
]

medicineMain/models.py
#coding=utf-8
from django.db import models
# Create your models here.
class XcxUser(models.Model):
    openid = models.CharField(max_length=255)
    session = models.CharField(max_length=255, blank=True)
    xcxCode=models.CharField(max_length=255, blank=True)
    xcxSession = models.CharField(max_length=255, blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    phone = models.CharField(u"手机", max_length=255, blank=True)
    passWord = models.CharField(u"密码", max_length=255, blank=True)
    gender = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    province = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    avatarUrl = models.CharField(max_length=255, blank=True)
    nickname = models.CharField(max_length=255, blank=True)
    code=models.CharField(max_length=255,blank=True)
    bodyChoices = ((-1, u'胃寒'), (0, u"胃中性"), (1, u'胃热'))
    body = models.IntegerField(u'身体状况', choices=bodyChoices, default=0)

    def __unicode__(self):
        return self.nickname
    class Meta:
        verbose_name=u"用户管理"
        verbose_name_plural=u"用户管理"
class CaseHistory(models.Model):
    xcxUserForeign=models.ForeignKey(XcxUser)
    name=models.CharField(u"姓名",max_length=255,blank=True)
    tel = models.CharField(u"联系电话", max_length=255, blank=True)
    height = models.CharField(u"身高", max_length=255, blank=True)
    weight = models.CharField(u"体重", max_length=255, blank=True)
    birthday = models.DateField(u'生日',blank=True,null=True)
    figure = models.CharField(u"体形", max_length=255, blank=True)
    sex=models.CharField(u'性别',max_length=255,blank=True)
    allergyHistory= models.TextField(u"过敏史",blank=True)
    medicalHistory = models.TextField(u'过去的过什么病',blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    physicalCondition=models.CharField(u"身体状况", max_length=255, blank=True)

    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name=u"病例管理"
        verbose_name_plural=u"病例管理"
class Symptom(models.Model):
    CaseHistoryForeign=models.ManyToManyField(CaseHistory,blank=True)
    symptomName=models.CharField(u"症状名",max_length=255)
    sickChoices = ((-1, u'胃寒'), (1, u'胃热'))
    sick=models.IntegerField(u'病症',choices=sickChoices,default=0)
    def __unicode__(self):
        return self.symptomName
    class Meta:
        verbose_name=u"症状管理"
        verbose_name_plural=u"症状管理"

class UserImage(models.Model):
    caseHistotyForeign=models.ForeignKey(CaseHistory,blank=True,null=True)
    image=models.ImageField(u'图片',upload_to='images', max_length=255)
    class Meta:
        verbose_name=u"用户图片"
        verbose_name_plural=u"用户图片"
class ScrollImage(models.Model):
    image=models.ImageField(u"图片",upload_to="images",max_length=255)
    imageDetail=models.ImageField(u"内部详情",upload_to="images",max_length=255,blank=True)
    url=models.URLField(u"跳转地址",blank=True)
    class Meta:
        verbose_name=u"滚动图片"
        verbose_name_plural=u"滚动图片"

class IndexImage(models.Model):
    image=models.ImageField(u"图片",upload_to="images",max_length=255)
    class Meta:
        verbose_name=u"首页图片"
        verbose_name_plural=u"首页图片"

class Message(models.Model):
    text=models.TextField(u"消息",max_length=255)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    class Meta:
        verbose_name=u"系统消息"
        verbose_name_plural=u"系统消息"
    def __unicode__(self):
        return self.text
class Address(models.Model):
    xcxUserForeign = models.ForeignKey(XcxUser)
    name=models.CharField(u"姓名",max_length=255)
    detailAddress=models.CharField(u"地址",max_length=255,blank=True)
    contact=models.CharField(u'电话',max_length=255,blank=True)
    province=models.CharField(u'省',max_length=255,blank=True)
    city=models.CharField(u'市',max_length=255,blank=True)
    district=models.CharField(u'区',max_length=255,blank=True)
    countyName=models.CharField(u'国',max_length=255,blank=True)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name=u"地址信息"
        verbose_name_plural=u"地址信息"

templates/addAddress.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/addAddress/addAddress.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>

    <script type="text/javascript">




    </script>
</head>
<body>



</body>
</html>

templates/bindCellphone.html
<html lang="zh">
<head>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/bindCellphone/bindCellphone.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../static/bindCellphone/bindCellphone.js"></script>

    <script type="text/javascript">




    </script>
</head>
<body>
<div class="page bindPhone-wrap" id="bindPhonePage" data-router="bindPhonePage">
 
  <div class="bind-new-tel-wrap" >
    <div class="verify-row" style="border-bottom: 1px solid #e5e5e5;">
      <label class="item-name">手机号</label><input class="code-tel"  placeholder="请输入手机号"/>
    </div>
    <div class="verify-row">
      <label class="item-name">验证码</label><input class="codeinupt" bindinput="inputNewCode" placeholder="请输入验证码"/><label class="get-code-btn" >获取验证码</label>
    </div>
    <label class="bind-new-tel-btn">绑定手机</label>
  
  </div>
</div>
</body>
</html>

templates/caseOrder.html
<!--pages/caseOrder/caseOrder.wxml-->
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/public.css">

    <link rel="stylesheet" href="../static/caseOrder/caseOrder.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>

    <script src="../static/caseOrder/caseOrder.js">




    </script>
</head>
<body>

<div class="container">

{% for foo in list %}



<a class='dialog-block-item' href="{{ foo.url }}">
<text class='item-text' id='text1'>{{foo.text}}</text>
<text class='item-text' id='text2'>{{foo.modDateTime}}</text>
{% if foo.url %}<div class="delete-button" type="button" data-id="{{ foo.id }}">删除</div>{% endif %}
</a>

    {% endfor %}



</div>
</body>
</html>

templates/caseTest.html
<!--caseTest.wxml-->
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/public.css">

    <link rel="stylesheet" href="../static/caseTest/caseTest.css">

    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src=" https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>


    <script src="../static/caseTest/caseTest.js"></script>
    <script type="text/javascript">


    </script>
</head>
<body>

<div class="container">
    <form id="subform" method='post' action="/casehis/">

        <div class="item-backgroud">
            <div class="dialog-block-item">
                <text class="item-label">姓名</text>
                <input id="name" name="name" type="text" class="edit-input" value="{{ name }}" {% if disable %}
                       disabled="disabled"{% endif %}/>

            </div>
            <div class="dialog-block-item">
                <text class="item-label">联系电话</text>
                <input  id="tel" name="tel" class="edit-input" value="{{ tel }}" {% if disable %}
                       disabled="disabled"{% endif %} />

            </div>
            <div class="dialog-block-item">
                <text class="item-label">身高(cm)</text>
                <input class="edit-input" name="height" value="{{ height }}"{% if disable %}
                       disabled="disabled"{% endif %} />

            </div>
            <div class="dialog-block-item">
                <text class="item-label">体重(kg)</text>
                <input class="edit-input" name="weight" value="{{ weight }}" {% if disable %}
                       disabled="disabled"{% endif %}/>

            </div>
        </div>
        <div class="item-backgroud">
            <div class="dialog-block-item">
                <text class="item-label">选择出生日期</text>
                <input class="pick" type="date" name="birthday" value="{{ birthday }}" {% if disable %}
                       disabled="disabled"{% endif %}/>

            </div>
            <select class="dialog-block-item pick" name="sex">
                <option value="请选择性别">请选择性别</option>
                <option value="男" {% ifequal sex "男" %}
                        selected="selected"
                {% endifequal %}>男
                </option>
                <option value="女" {% ifequal sex "女" %}
                        selected="selected"
                {% endifequal %}>女
                </option>
            </select>

            <select class="dialog-block-item pick" name="figure">
                <option value="请选择性别">请选择体形</option>
                <option value="正常" {% ifequal figure "正常" %}
                        selected="selected"
                {% endifequal %}>正常</option>
                <option value="偏瘦" {% ifequal figure "偏瘦" %}
                        selected="selected"
                {% endifequal %}>偏瘦</option>
                <option value="偏" {% ifequal figure "瘦" %}
                        selected="selected"
                {% endifequal %}>瘦</option>
                <option value="偏胖" {% ifequal figure "偏胖" %}
                        selected="selected"
                {% endifequal %}>偏胖</option>
                <option value="胖" {% ifequal figure "胖" %}
                        selected="selected"
                {% endifequal %}>胖</option>
            </select>


        </div>


        <div class="item-backgroud">

            <div class="dialog-block-item-big">
                <text class="item-label">填写过敏史</text>
                <textarea class="edit-textarea" name="allergyHistory">{{allergyHistory}}</textarea>
            </div>
        </div>
        <div class="item-backgroud">

            <div class="dialog-block-item-big">
                <text class="item-label">过去得过什么病</text>
                <textarea class="edit-textarea" name="medicalHistory">{{medicalHistory}}</textarea>

            </div>
        </div>

        <div class="item-backgroud">
            <text class="item-label">上传二张舌苔照片(要求：自然光线下，放松）</text>
            <div class="image-item">

                <img src="{{ userimage_set.0.image|default:'../static/images/upimage_03.png' }}"style="transform:rotate(90deg)" catchtap="upimage1"
                       class="upimage" id="image1" >
                    {% if not disable  %}
                    <input type="file"   capture="camera" class="upload-input" id="upload"  accept="image/*"/>
{% endif %}
                     </img>
                <img src="{{ userimage_set.1.image|default:'../static/images/upimage_03.png' }}" id="image2" catchtap="upimage2"
                       class="upimage"  style="transform:rotate(90deg)">
                    {% if not disable %}
                    <input type="file"  capture="camera" style="margin-left: 110px" class="upload-input" id="upload2"  accept="image/*"/></img>
                    {% endif %}
            </div>
        </div>

        <div class="item-backgroud">

            <text class="item-label">选择症状 (最少不低于六项)</text>

            <div class="dialog-block-item item-symptom">
                {% for foo in symptom_set %}




                    <button type="button" class="item-symptom-button {% if foo.select %}item-symptom-button-selectd{% endif %}"
                            data-id="{{ foo.id }}"data-sick="{{ foo.sick }}" {% if disable %}
                            disabled="disabled"{% endif %}>{{ foo.symptomName }} </button>


                {% endfor %}
            </div>

            <div class="dialog-block-item">
                <text class="item-label">身体状况:</text>
                <text class="item-label" id="sickspan">{{ physicalCondition }}</text>
            </div>
        </div>

        {% if not disable %}
            <button class="btn btn-block button" id="sub" type="button">提交</button>
        {% endif %}

    </form>

</div>
<div class="deatil-div">
    <img class="detail" />
    <div class="close">关闭 X</div>
    <div class="text-detail">长按图片保存</div>
</div>
</body>
</html>

templates/detail.html
<!--detail.wxml-->
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/addAddress/addAddress.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>

    <script type="text/javascript">




    </script>
</head>
<body>
<image style="width: 100%" src="{{ ruquest.GET.image}}"></image>
</body>
</html>

templates/index.html
<!--index.wxml-->
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/index/index.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../static/index/index.js"></script>

    <script type="text/javascript">




    </script>
</head>
<body>

<div class="container">
  <image  src="{{indexImage}}" id="image2"/>

  <div class="block">
  <a href="/caseTest/?session_key={{ session_key }}" class="inner-content" catchtap="test">

          <image class="list-img" src="../static/images/index_08.jpg"  mode="aspectFit"></image>
          <div class="title-container">
            <div class="title">我的自测</div>

            
        </div>
      
  </a>
      <a href="/caseOrder/?session_key={{ session_key }}&type=case" class="inner-content" catchtap="mycase">
          
          <image class="list-img" src="../static/images/index_05.jpg"  mode="aspectFit"></image>
          <div class="title-container" >
            <div class="title">自测档案</div>
            
        </div>
      
  </a>
  </div>

<div id="lunbo">

        {% for image in imagelist %}

<a class="slide-a" href="{{ image.url }}"> <img class="slide-image" src="{{ image.image }}"></a>

    {% endfor %}

</div>



</div>
</body>
</html>

templates/myAddress.html
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/public.css">

    <link rel="stylesheet" href="../static/myAddress/myAddress.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>

    <script src="../static/distpicker.js"></script>
    <script src="../static/myAddress/myAddress.js"></script>
    <script type="text/javascript">


    </script>
</head>
<body>

<div class="myAddress-wrap page" id="myAddress">
    <div class="myAddress-content-container">
        <div class="myAddress-address-list">

            {% for foo in list %}
                <div class="myAddress-address">
                    <label class="check-box-container" data-id="{{ foo.id }}">

                    </label>
                    <div class="myAddress-address-top">
                        <text class="inline">{{ foo.name }}</text>
                        <text class="inline">{{ foo.contact }}</text>
                        <div class="inline">{{ foo.detailAddress }}</div>
                    </div>

                </div>
            {% empty %}

                <div style="color:#a8a8a8; padding:20px;">暂无地址</div>
            {% endfor %}


        </div>
    </div>
    <div class="myAddress-bottom-nav">添加新地址</div>
</div>

<form bindsubmit="formSubmit" class="formaddress" id="formaddressa">
    <div class="addAddress-edit-wrap">
        <div class="addAddress-content-container">
            <div style="padding:7px;background:#fff;">

                <div class="dialog-block-item">
                    <text class="item-label">收货人</text>
                    <input class="addAddress-edit-input" name="name" id="name"/>
                </div>
                <div class="dialog-block-item">
                    <text class="item-label">联系电话</text>
                    <input class="addAddress-edit-input" name="contact" id="contact"/>
                </div>
                <div class="dialog-block-item">
                    <div class="item-label">所在地区</div>
                    <div class="picker-container" data-toggle="distpicker">
                        <select data-province="---- 选择省 ----" name="province" id="province"></select>
                        <select data-city="---- 选择市 ----" name="city" id="city"></select>
                        <select data-district="---- 选择区 ----" name="district" id="district"></select>
                    </div>
                </div>
                <div class="dialog-block-item">
                    <text class="item-label">详细地址</text>
                    <textarea class="addAddress-edit-input" name="detailAddress" id="detailAddress"></textarea>
                </div>

            </div>
        </div>
    </div>
    <div class="addAddress-bottom-opt">
        <div id="addresssave"class="btn btn-block btn-red" type="button">保存</>
    </div>
</form>

</body>

</html>

templates/nav.html
<div style="line-height:37px;padding-right:40px;color:white;text-align:center;width: 100%;height: 37px;background: black">
    <div href="#" style="padding-left:10px;padding-right:40px;font-size:20px;float:left;color: white;line-height: 37px" onClick="javascript :history.back(-1);">⟨</div>
   {{ title }}
</div>

templates/page10070.html
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/public.css">
    <link rel="stylesheet" href="../static/page10070/page10070.css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../static/page10070/page10070.js"></script>
    <script type="text/javascript">




    </script>
</head>
<body>

<div class="app">
<div name="zcUserCenter">
  <div class="user-center usercenter-mode1 background-ele" >
    <div class="show-div" data-router="userCenter"
          style=" background-image: url('http://cdn.jisuapp.cn/zhichi_frontend/static/webapp/images/top_bg.jpg');"> <label class="empty-span"></label>
        <div class="show"> <image class="cover-thumb" src="{{ avatarUrl|default:'http://img.zhichiwangluo.com/zc_app_default_photo.png'}}"></image>
      <label style="color: white" class="nickname">{{nickname|default:'用户名' }}</label></div>

    
    </div>
      <a href="/myAddress/?session_key={{ session_key }}"class="line">
          <label class="ico-moon icon-location"></label>
          <span>收货地址</span>
          <label class="ico-moon icon-rightarrow"></label>
      </a>
      <a href="/caseOrder/?session_key={{ session_key }}&type=case" class="line">
          <label class="ico-moon icon-notebook"></label>
          <span>自测档案</span>
          <label class="ico-moon icon-rightarrow"></label>
      </a><a href="/userinfo1/?session_key={{ session_key }}&type=case" class="line">
          <label class="ico-moon icon-notebook"></label>
          <span>个人档案</span>
          <label class="ico-moon icon-rightarrow"></label>
      </a>
      <a href="/caseOrder/?session_key={{ session_key }}&type=message" class="line">
          <label class="ico-moon icon-notify"></label>
          <span>系统消息</span>
          <label class="ico-moon icon-rightarrow"></label>
      </a>
      <div class="line">
          <label class="ico-moon icon-notify"></label>
          <span>关于我们</span>
          <label class="ico-moon icon-rightarrow"></label>
      </div>



  </div>
</div>
<img class="detail" src="{{ image }}">
</div>

templates/userinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">


    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/public.css">

    <link rel="stylesheet" href="../static/caseTest/caseTest.css">

    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src=" https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>





</head>
<body>
<div class="content">
     <div class="item-backgroud">
            <div class="dialog-block-item">
                <text class="item-label">姓名:{{  nickname}}</text>


            </div>
            <div class="dialog-block-item">
                <text class="item-label">城市:{{ city }}</text>



            </div>
            <div class="dialog-block-item">
                <text class="item-label">省:{{ province }}</text>



            </div>
            <div class="dialog-block-item">
                <text class="item-label">国家:{{  country}}</text>



            </div>
        <div class="dialog-block-item">
                <a class="item-label" href="/bindCellPhone/?session_key={{ session_key }}">{% if phone %} 联系电话:{% endif %}{{ phone|default:"点此处绑定手机" }}</a>



            </div>
        </div>



</div>

</body>
</html>